name: deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/deploy.yaml"
      - "nimble_school/**"

env:
  ELIXIR_VERSION: 1.14
  OTP_VERSION: 25
  EXAMPLE_PROJECT: nimble_school

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.EXAMPLE_PROJECT }}
    steps:
      - uses: actions/checkout@v2

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.OTP_VERSION }}
          elixir-version: ${{ env.ELIXIR_VERSION }}

      - uses: actions/cache@v2
        id: mix-cache
        with:
          path: |
            ${{ env.EXAMPLE_PROJECT }}/deps
            ${{ env.EXAMPLE_PROJECT }}/_build
          key: ${{ runner.os }}-${{ env.OTP_VERSION }}-${{ env.ELIXIR_VERSION }}-mix-${{ hashFiles('${{ env.EXAMPLE_PROJECT }}/**/mix.lock') }}

      - run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
        if: steps.mix-cache.outputs.cache-hit != 'true'

      - name: Build Site
        run: mix freeze && ls -la _freeze

      - name: Archive Site
        uses: actions/upload-artifact@v2
        with:
          name: site
          path: ${{ env.EXAMPLE_PROJECT }}/_freeze

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Site
        uses: actions/download-artifact@v2
        with:
          name: site
          path: _freeze

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: _freeze
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
